# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
filter-run-always: &filter-run-always
  filters:
    tags:
      only: /.*/

filter-run-on-master-and-version-tag-only: &filter-run-on-master-and-version-tag-only
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

aliases:
  - &step-checkout
    checkout
  - &step-restore-cache 
    restore_cache:
      keys:
      - v1-dependencies-{{ checksum "package.json" }}
      - v1-dependencies-
  - &step-install
    run: yarn install
  - &step-save-cache
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}
  - &step-build
    run: yarn build
  
build-node-common: &common-build
  working_directory: ~/repo
  steps:
    - *step-checkout
    - *step-restore-cache
    - *step-install
    - *step-save-cache
    - *step-build
    - run:
        name: Testing
        command: yarn test

version: 2
jobs:
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    steps:
      - *step-checkout
      - *step-restore-cache
      - *step-install
      - *step-save-cache
      - *step-build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

  build-node8:
    <<: *common-build
    docker:
      - image: circleci/node:8

  build-node9:
    <<: *common-build
    docker:
      - image: circleci/node:9

  build-node10:
    <<: *common-build
    docker:
      - image: circleci/node:10

  build-node11:
    <<: *common-build
    docker:
      - image: circleci/node:11

workflows:
  version: 2
  build_all:
    jobs:
      - build-node8:
          <<: *filter-run-always
      - build-node9:
          <<: *filter-run-always
      - build-node10:
          <<: *filter-run-always
      - build-node11:
          <<: *filter-run-always
      - deploy:
          requires:
            - build-node8
            - build-node9
            - build-node10
            - build-node11
          <<: *filter-run-on-master-and-version-tag-only
