version: "3"
services:
    app:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - ..:/examples
        environment:
            - AVIAN_APP_HOME=/examples/hello-world
            - AVIAN_APP_REDIS_HOST=cache
        depends_on:
            - cache
    cache:
        image: redis:alpine
