version: "3"
services:
    app:
        build: ../../
        image: flypapertech/avian:latest
        ports:
            - "8080:8080"
        volumes:
            - ..:/app
        environment:
            - AVIAN_APP_HOME=/app
